### PR TITLE
Add custom event types

### LINKED ISSUE #146: Allow the registration of custom event types
Currently the event types that are accessible via `on<event>` are hard coded as an array in the `DomEventDelegate`. Would it be viable to allow the registration of custom events so that the use of `on<event>` could be expanded beyond that hard coded array?

It goes without saying that the events would have to be registered prior to the initialization of the module attempting to use said events. There's also the fact that only events that bubble would work, so it might be best to pass in the actual event object and ensure that bubbling is `true` for that event. 

Thoughts?

### PR DESCRIPTION
**Pull request by j3tan**
Adds a new param to Box.Application.init() - eventTypes: [...events...]

fixes #146

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @j3tan has signed the CLA. Thanks for the pull request!

**Comment by j3tan** [comment]
I could not implement the `event.bubbles` check for two reasons:

1. jQuery events do not have .bubbles attribute for most of their events (i.e. click)
2. `Box.Application.error()` method is not accessible via the `DomEventDelegate` object.

**Comment by nzakas** [comment]
You can use the `originalEvent` property on a jQuery event object to get the native event, which should always have `bubbles`. (If you want to do that check.)

Otherwise, :+1:

**Comment by j3tan** [comment]
Good idea, however, DOMEventDelegate would then need to do some jQuery object checking such as `!event.bubbles && !(event.originalEvent && event.originalEvent.bubbles)`. The current implementation is also agnostic of the Box.DOM implementation so I would like to maintain for the time being. We'll add a disclaimer to the documentation page when I update it.

**Pull request merged**
