### PR TITLE
Fix typo in Getting Started / Service docs (fixes #69)

### LINKED ISSUE #69: Typo in Getting Started / Service Documentation
`isValidNumer()` should be `isValidNumber()`

I’d be happy to fix this :)

### PR DESCRIPTION
**Pull request by domchristie**

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @domchristie, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by domchristie** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @domchristie has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by j3tan** [comment]
Thanks!

**Pull request merged**
