### PR TITLE
Use CommonJS in lib files and export new bundle

### LINKED ISSUE #24: Load via npm as module
Now, there is no way to load ```t3js``` properly via browserify or webpack, as package.json does not have any main file entry, so I can't just write:
```javascript
import Box from "t3js";
```

But it would be very nice to have such opportunity (not to use global Box variable, but the one exported by module).

### PR DESCRIPTION
**Pull request by j3tan**
- adding proxyquire for testing browserified source files
- modified tests to use CommonJS
- modified build process to account for browserification
- downgraded karma-coverage to 0.2.6 to support browserify-istanbul
- updated ESLint rules to account for CommonJS changes

fixes #24

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @j3tan, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by j3tan** [comment]
I'll fix the tests later (I think proxyquire-universal will need to be removed since its causing issues).

browserify is nice but it adds a ton of overhead to implement including:
1. Compilation step when building
1. Compilation step when testing
1. Various plugins to support browserified code

You can require('t3js') but the maintenance cost might be pretty high

**Comment by j3tan** [comment]
Alternatively, we can just wrap what we had before in something like

lib/box.js
if (module && module.exports) { 
  module.exports = Box;
}

**Comment by mbinette** [comment]
Since we are going the Browserify route, how about writing these as ES6 modules. ES6 can be transpiled by babel using Browserify just as easy as CommonJS and can also be transpiled to CommonJS if needed as well. Starting at CommonJS doesn't allow us to transpile to ES6. None of the other features in ES6 need to be used so the remaining code would look similar to your changes made for CommonJS.

**Comment by priyajeet** [comment]
I don't think we should be jumping the gun on using ES6 modules and add more to the above mentioned overhead. Specially when an ES3 browser also needs to be supported and Babel only goes as far back as ES5. Should also at least let TC39 pass the ES6 spec, hopefully it won't be like last June when they postponed it by an year.

**Comment by mbinette** [comment]
Does going to CommonJS have the same problem with ES3? I figured that ES6 modules (and only the module syntax) can easily be transpiled to CommonJS so that a CommonJS version doesn't need to be manually maintained. If no other ES6 features are used then won't the transpile work in ES3 browsers? It certainly should since Browserify is doing the same thing with ES6 modules as it is doing with CommonJS modules. I like all the changes made here for CommonJS where it eliminates the Box.Application type of definition.

I'm also not 100% up on ES6 everything but would like to write my Modules, Services, and Behaviors in ES6 knowing they will need to be transpiled prior to use. I really like the simplicity of T3 but haven't done enough to know how to write ES6 Modules, Services, and Behaviors and have them work with T3 after a transpile. I'll have to do some experimenting.

**Comment by nzakas** [comment]
@mbinette there's no real tangible value of using ES6 modules over CommonJS for our purpose. I don't think it's with the effort at this point.

@j3tan you also need to add a "main" field to package.json that pints to box.js as the entry point for the package. Up to you if you'd rather just wrap the existing bundle to load in node or finish this up. Either way works.

**Comment by j3tan** [comment]
I've added the `main` file but I'm not entirely convinced that CommonJS is a good fit right now. The added amount of work including browserify plugins for coverage and karma make it much less appealing. I'm going to test out a simple wrapper for the existing bundle to compare

**Comment by j3tan** [comment]
https://github.com/box/t3js/pull/40 - alternate approach

**Comment by nzakas** [comment]
Yeah, #40 looks like a much simpler way to go for the moment.

**Pull request closed without merging**
