### PR TITLE
Optimize circular dependencies check

### PR DESCRIPTION
**Pull request by rodenis**
I think that may be more effective to check on circular dependencies only during instantiation of service. When an instance of service already exists we should immediately return it.

P.S. Changes only in lib/application.js file

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @rodenis, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by rodenis** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @rodenis has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by nzakas** [comment]
Thanks! I'm not sure I understand the purpose of this change - can you explain the problem you were having?

**Comment by rodenis** [comment]
There is no problem with your code. It just a performance tweak. The idea is not to check for circular deps every time you call getService method, but to check once during 1st call.

**Comment by nzakas** [comment]
Ah, I see. Thanks for explaining. Can you revert the changes in `dist`? These are only updated when we do a release.

@j3tan any other thoughts?

**Comment by j3tan** [comment]
looks fine to me! just need the revert of dist/

**Comment by rodenis** [comment]
I've just reverted changes in dist

**Comment by nzakas** [comment]
Looks like we're all set now, thanks!

**Pull request merged**
