### PR TITLE
Added new method to report console info messages in debug mode (#175)

### PR DESCRIPTION
**Pull request by guumo**
I added the reportInfo method to display information messages when the debug mode is enabled.

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @guumo, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by guumo** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @guumo has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by guumo** [comment]
:) Thanks!

2016-07-13 15:23 GMT+02:00 Box CLA Bot <notifications@github.com>:

**Comment by j3tan** [comment]
lgtm

**Pull request merged**
