### PR TITLE
Update t3.js

### PR DESCRIPTION
**Pull request by rootsher**
Look here, to my own event emitter implementation: https://github.com/rootsher/event-emitter

In off method the "for" loop end works when find first handler..so...what will be when handler exists more than once? I modify code to remove each handler in iterating array. Also when we remove off handler, the array can be empty, so..we can delete type key from object.

You can also add context parameter to "on" method and more data parameters (using Array.prototype.slice.call(arguments, 1)) to "fire" method.

You can use my code, pull request in your project. I will be very happy ;)

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @rootsher, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by rootsher** [comment]
CLA signed ! :)

**Comment by boxcla** [comment]
Verified that @rootsher has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by priyajeet** [comment]
Quick glance, dist/* files are generated files. You should not be modifying them manually. Source files are inside lib/*. Also, your changes break IE8 compatibility due to the use of Array.isArray() and Array.prototype.filter()

**Comment by rootsher** [comment]
Okay, thanks, I create new pull request (https://github.com/box/t3js/pull/34), please close this.

**Pull request closed without merging**
