### PR TITLE
Adding missing doctype Fixes #14

### LINKED ISSUE #14: Adding missing doctype in todo example

### PR DESCRIPTION
**Pull request by priyajeet**

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @priyajeet, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by priyajeet** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @priyajeet has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by nzakas** [comment]
Thanks!

**Pull request merged**
