### PR TITLE
readme grammar

### PR DESCRIPTION
**Pull request by diffsky**
possessive form of "its" doesn't take an apostrophe

### CODE REVIEW

**Comment by boxcla** [comment]
Hi @diffsky, thanks for the pull request. Before we can merge it, we need you to sign our Contributor License Agreement. You can do so electronically here: http://opensource.box.com/cla

Once you have signed, just add a comment to this pull request saying, "CLA signed". Thanks!

**Comment by diffsky** [comment]
CLA signed

**Comment by boxcla** [comment]
Verified that @diffsky has just signed the CLA. Thanks, and we look forward to your contribution.

**Comment by nzakas** [comment]
Thanks!

**Pull request merged**
